//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscolaColetorWeb.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class escolaEntities : DbContext
    {
        public escolaEntities()
            : base("name=escolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluno> aluno { get; set; }
        public virtual DbSet<chamada> chamada { get; set; }
        public virtual DbSet<responsavel> responsavel { get; set; }
        public virtual DbSet<turma> turma { get; set; }
    
        public virtual ObjectResult<sp_lista_chamada_Result> sp_lista_chamada(Nullable<System.DateTime> data, Nullable<int> turma)
        {
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            var turmaParameter = turma.HasValue ?
                new ObjectParameter("turma", turma) :
                new ObjectParameter("turma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lista_chamada_Result>("sp_lista_chamada", dataParameter, turmaParameter);
        }
    }
}
