//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColetorGui
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class escolaEntities : DbContext
    {
        public escolaEntities()
            : base("name=escolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluno> aluno { get; set; }
        public virtual DbSet<chamada> chamada { get; set; }
        public virtual DbSet<responsavel> responsavel { get; set; }
        public virtual DbSet<turma> turma { get; set; }
        public virtual DbSet<vw_chamada> vw_chamada { get; set; }
    }
}
