//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColetorGui
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_chamada
    {
        public System.DateTime dt_chamada { get; set; }
        public int cd_aluno { get; set; }
        public string nm_aluno { get; set; }
        public bool in_presente { get; set; }
        public int cd_responsavel { get; set; }
        public string nm_responsavel { get; set; }
        public int cd_turma { get; set; }
        public string dc_turma { get; set; }
    }
}
